import pandas as pd
import numpy as np
from datetime import datetime

# ═══════════════════════════════════
# LOAD CLEAN DATA
# Use your cleaned CSV from Day 11
# ═══════════════════════════════════

try:
    df = pd.read_csv("well_data_cleaned.csv")
    print("Clean data loaded successfully.")
except FileNotFoundError:
    # If cleaned file not found,
    # create data directly
    data = {
        "Well_Name": ["Well_Alpha", "Well_Beta",
                      "Well_Gamma", "Well_Delta",
                      "Well_Epsilon", "Well_Zeta",
                      "Well_Eta"],
        "Location": ["Northern Block",
                     "Southern Block",
                     "Northern Block",
                     "Eastern Block",
                     "Southern Block",
                     "Eastern Block",
                     "Northern Block"],
        "Type": ["Oil", "Oil", "Gas Condensate",
                 "Oil", "Oil",
                 "Gas Condensate", "Oil"],
        "Avg_Daily_Barrels": [520, 303, 742,
                              179, 634, 289, 891],
        "Days_Active": [365, 280, 410, 190,
                        320, 245, 400],
        "Water_Cut": [0.15, 0.22, 0.08, 0.45,
                      0.18, 0.35, 0.11],
        "Status": ["Active", "Active", "Active",
                   "Review needed", "Active",
                   "Review needed", "Active"]
    }
    df = pd.DataFrame(data)
    print("Using built-in dataset.")


# ═══════════════════════════════════
# REPORT GENERATION FUNCTIONS
# ═══════════════════════════════════

def generate_header(field_name="Northern Field"):
    """Generate professional report header."""
    now = datetime.now()
    date_str = now.strftime("%d %B %Y")
    time_str = now.strftime("%H:%M")

    header = f"""
{'='*60}
         FIELD PRODUCTION STATUS REPORT
{'='*60}
  Field Name  : {field_name}
  Report Date : {date_str}
  Report Time : {time_str}
  Generated By: Production Data System v1.0
{'='*60}
"""
    return header


def generate_executive_summary(df):
    """
    Generate executive summary —
    the 5 numbers a manager needs first.
    """
    active = df[df["Status"] == "Active"]
    review = df[df["Status"] == "Review needed"]
    total_prod = df["Avg_Daily_Barrels"].sum()
    active_prod = active["Avg_Daily_Barrels"].sum()
    avg_water_cut = df["Water_Cut"].mean() * 100

    # Calculate field efficiency
    # (active production / total capacity)
    efficiency = (active_prod / total_prod) * 100

    summary = f"""
EXECUTIVE SUMMARY
{'-'*60}
  Total Field Production : {total_prod:,} bbl/day
  Active Well Production : {active_prod:,} bbl/day
  Wells Active           : {len(active)} of {len(df)}
  Wells Under Review     : {len(review)}
  Average Water Cut      : {avg_water_cut:.1f}%
  Field Efficiency       : {efficiency:.1f}%
{'-'*60}
"""
    return summary


def generate_well_status_table(df):
    """Generate formatted well status table."""

    table = f"""
WELL STATUS TABLE
{'-'*60}
{'Well':<15} {'Prod(bbl/d)':>12} {'WC%':>6} \
{'Days':>6} {'Status':<15}
{'-'*60}
"""

    # Sort by production — highest first
    df_sorted = df.sort_values(
        "Avg_Daily_Barrels", ascending=False
    )

    for _, row in df_sorted.iterrows():
        # Add warning flag for high water cut
        wc_flag = " ⚠" if row["Water_Cut"] > 0.35 else ""

        table += (
            f"  {row['Well_Name']:<13} "
            f"{row['Avg_Daily_Barrels']:>12,.0f} "
            f"{row['Water_Cut']*100:>5.1f}% "
            f"{row['Days_Active']:>6} "
            f"  {row['Status']}{wc_flag}\n"
        )

    table += f"{'-'*60}\n"
    table += (
        f"  {'TOTAL':<13} "
        f"{df['Avg_Daily_Barrels'].sum():>12,.0f}\n"
    )
    table += f"{'-'*60}\n"

    return table


def generate_performance_rankings(df):
    """Generate top and bottom performers."""

    top_3 = df.nlargest(3, "Avg_Daily_Barrels")
    bottom_3 = df.nsmallest(3, "Avg_Daily_Barrels")

    rankings = f"""
PERFORMANCE RANKINGS
{'-'*60}
TOP 3 PRODUCERS:
"""
    for i, (_, row) in enumerate(
        top_3.iterrows(), 1
    ):
        rankings += (
            f"  {i}. {row['Well_Name']:<15} "
            f"{row['Avg_Daily_Barrels']:>6,.0f} bbl/day"
            f"  ({row['Location']})\n"
        )

    rankings += f"\nBOTTOM 3 PRODUCERS:\n"
    for i, (_, row) in enumerate(
        bottom_3.iterrows(), 1
    ):
        rankings += (
            f"  {i}. {row['Well_Name']:<15} "
            f"{row['Avg_Daily_Barrels']:>6,.0f} bbl/day"
            f"  ({row['Location']})\n"
        )

    rankings += f"{'-'*60}\n"
    return rankings


def generate_risk_flags(df):
    """Identify and flag wells requiring attention."""

    flags = f"""
RISK FLAGS — WELLS REQUIRING ATTENTION
{'-'*60}
"""

    # Flag high water cut
    high_wc = df[df["Water_Cut"] > 0.35]
    if len(high_wc) > 0:
        flags += "⚠ HIGH WATER CUT (>35%):\n"
        for _, row in high_wc.iterrows():
            flags += (
                f"  → {row['Well_Name']}: "
                f"{row['Water_Cut']*100:.0f}% water cut\n"
                f"    Action: Review production "
                f"optimisation options\n"
            )

    # Flag low production wells
    low_prod = df[
        (df["Avg_Daily_Barrels"] < 200) &
        (df["Status"] == "Active")
    ]
    if len(low_prod) > 0:
        flags += "\n⚠ LOW PRODUCTION (<200 bbl/day):\n"
        for _, row in low_prod.iterrows():
            flags += (
                f"  → {row['Well_Name']}: "
                f"{row['Avg_Daily_Barrels']:.0f} bbl/day\n"
                f"    Action: Evaluate stimulation\n"
            )

    # Flag review status wells
    review = df[df["Status"] == "Review needed"]
    if len(review) > 0:
        flags += "\n⚠ WELLS UNDER REVIEW:\n"
        for _, row in review.iterrows():
            flags += (
                f"  → {row['Well_Name']}: "
                f"Status requires resolution\n"
            )

    if len(high_wc) == 0 and \
       len(low_prod) == 0 and \
       len(review) == 0:
        flags += "  ✓ No critical issues identified\n"

    flags += f"{'-'*60}\n"
    return flags


def generate_recommendations(df):
    """Generate data-driven recommendations."""

    active = df[df["Status"] == "Active"]
    avg_prod = active["Avg_Daily_Barrels"].mean()
    high_wc = df[df["Water_Cut"] > 0.35]
    top_well = df.loc[
        df["Avg_Daily_Barrels"].idxmax()
    ]

    recs = f"""
RECOMMENDATIONS
{'-'*60}
"""
    rec_num = 1

    if len(high_wc) > 0:
        recs += (
            f"  {rec_num}. PRIORITY — Water Cut Management\n"
            f"     {len(high_wc)} well(s) exceed 35% "
            f"water cut threshold.\n"
            f"     Initiate water injection review and\n"
            f"     consider chemical treatment options.\n\n"
        )
        rec_num += 1

    recs += (
        f"  {rec_num}. Production Optimisation\n"
        f"     {top_well['Well_Name']} leads field "
        f"at {top_well['Avg_Daily_Barrels']:,.0f} bbl/day.\n"
        f"     Review completion strategy for "
        f"application to underperforming wells.\n\n"
    )
    rec_num += 1

    recs += (
        f"  {rec_num}. Field Monitoring\n"
        f"     Field average: {avg_prod:,.0f} bbl/day "
        f"per active well.\n"
        f"     Recommend weekly production review\n"
        f"     to track water cut trends early.\n"
    )

    recs += f"\n{'-'*60}\n"
    return recs


def generate_footer():
    """Generate report footer."""
    footer = f"""
  Report generated: {datetime.now().strftime('%d %B %Y %H:%M')}
  Data source: Field Production Database
  Prepared by: Production Analytics Team
  Classification: Internal Use Only
{'='*60}
    END OF REPORT
{'='*60}
"""
    return footer


# ═══════════════════════════════════
# GENERATE COMPLETE REPORT
# ═══════════════════════════════════

def generate_full_report(df,
                         field_name="Northern Field",
                         save_to_file=True):
    """Generate and optionally save full report."""

    # Build report section by section
    report = ""
    report += generate_header(field_name)
    report += generate_executive_summary(df)
    report += generate_well_status_table(df)
    report += generate_performance_rankings(df)
    report += generate_risk_flags(df)
    report += generate_recommendations(df)
    report += generate_footer()

    # Print to screen
    print(report)

    # Save to text file
    if save_to_file:
        filename = (
            f"field_report_"
            f"{datetime.now().strftime('%Y%m%d_%H%M')}"
            f".txt"
        )
        with open(filename, "w") as f:
            f.write(report)
        print(f"\nReport saved as: {filename}")

    return report


# Run the report generator
generate_full_report(df, "Northern Field")